kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: efs-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: efs-provisioner
    spec:
      containers:
        - name: efs-provisioner
          image: quay.io/external_storage/efs-provisioner:v0.1.0
          env:
            - name: FILE_SYSTEM_ID
              value: ##your-efs-id##
            - name: AWS_REGION
              value: us-west-2
            - name: PROVISIONER_NAME
              value: eks/aws-efs
          volumeMounts:
            - name: pv-vol
              mountPath: /persistentvolumes
      volumes:
        - name: pv-vol
          nfs:
            server: ##fs-xxxxxx.efs.us-west-2.amazonaws.com##
            path: /
