persistence:
  enabled: true
  size: "3Gi"
master:
  tag: "2.222.4"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hostName: jenkins.kubernetes.tn
    jenkinsUrl: "https://jenkins.kubernetes.tn"
  adminPassword: HelloWorld
  overwritePlugins: true
  installPlugins:
    - kubernetes:1.25.7
    - workflow-job:2.39
    - workflow-aggregator:2.6
    - credentials-binding:1.22
    - git:4.2.2
    - configuration-as-code:1.41