apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-demo
  region: us-east-1
  version: "1.16"
vpc:
  id: "vpc-055992cff09c5d913"
  cidr: "172.32.0.0/16"
  subnets:
    private:
      us-east-1a:
          id: "subnet-08810775fd4b21034"
          cidr: "172.32.2.0/24"
      us-east-1b:
          id: "subnet-0fd70446ec3c6588a"
          cidr: "172.32.3.0/24"

nodeGroups:
  - name: spot-ng
    labels:
      lifecycle: Ec2Spot
    #taints:
    #  spotInstance: true:PreferNoSchedule
    privateNetworking: true
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
    volumeSize: 5
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    instancesDistribution: 
      instanceTypes:
        - t3.large
        - t3.medium
        - t3.small
        - t3a.medium
        - t3a.large
        - t3a.small
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0 
      spotAllocationStrategy: capacity-optimized
    iam:
      withAddonPolicies:
        externalDNS: true
        autoScaler: true
        ebs: true
        efs: true
        cloudWatch: true
        albIngress: true