---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-configmap"
data:
  superSecretValue: "{{ .Release.Name }}-{{ .Release.Revision }}-{{ .Values.asdfcomplex.qwert | default "asdf" }}-idgafos"
  {{- if and .Values.asdf (eq .Values.asdf "qwerty") }}
  anotherSecret: "sadf"
  {{- end }}
  aSetOfValues: |-
    {{- range .Values.lotsOfValues }}
    - {{ . }}
    {{- end }}
  someDateField: {{ now | htmlDate }}
  superSecretField: {{ randAlphaNum 32 | b64enc | b64dec }}
  genericPass: {{ .Values.global.genericPass }}
