apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-demo
  region: us-east-1
  
managedNodeGroups:
  - name: eks-ng-17
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    instanceType: t3.small
    volumeSize: 5
    privateNetworking: true
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
      #sourceSecurityGroupIds: ["sg-0e10bb986d85449b8"]
    labels: {env: dev}
    tags:
      costid: devops
    iam:
      withAddonPolicies:
        externalDNS: true
        autoScaler: true
        ebs: true
        efs: true
        cloudWatch: true
        albIngress: true