apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  labels:
    name: aws-cli
  annotations:
    iam.amazonaws.com/role: <ROLE>
spec:
  containers:
    - image: cgswong/aws:aws
      command:
        - "sleep"
        - "9999"
      name: aws-cli
