apiVersion: v1
kind: Service
metadata:
  name: numbers-web
  namespace: rng
  labels:
    app: numbers-web
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: numbers-web
  type: ClusterIP