apiVersion: v1
kind: Service
metadata:
  name: node-app
  labels:
      env: prod
spec:
  type: LoadBalancer
  selector:
    app: node-app
    deployment: blue
  ports:
  - port: 80
    targetPort: 8080