apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-blue
spec:
  replicas: 3
  selector:
      matchLabels:
        app: node-app
        deployment: blue
  template:
    metadata:
      labels:
        app: node-app
        deployment: blue
    spec:
      containers:
      - image: node-app:1.0
        name: node-app
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        resources: {}