apiVersion: v1
kind: Service
metadata:
  name: node-app-green-test
  labels:
      env: test
spec:
  type: LoadBalancer
  selector:
    app: node-app
    deployment: green
  ports:
  - port: 9000
    targetPort: 8080