apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxhello-blue
  labels:
    app.kubernetes.io/name: nginxhello-blue
    app.kubernetes.io/part-of: nginxhello-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginxhello-blue
      app.kubernetes.io/part-of: nginxhello-blue
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginxhello-blue
        app.kubernetes.io/part-of: nginxhello-blue
    spec:
      containers:
      - name: nginxhello-blue
        image: nbrown/nginxhello:mainline
        ports:
        - containerPort: 80
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: COLOR
          value: blue
      hostname: internal-nginxhello-blue
---
apiVersion: v1
kind: Service
metadata:
  name: nginxhello-blue
  labels:
    app.kubernetes.io/name: nginxhello-blue
    app.kubernetes.io/part-of: nginxhello-blue
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: nginxhello-blue
    app.kubernetes.io/part-of: nginxhello-blue
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: internal-ingress
spec:
  rules:
  - host: <insert name associated with load balancer>
    http:
      paths:
      - backend:
          serviceName: nginxhello-blue
          servicePort: 80
