apiVersion: v1
kind: Service
metadata:
  name: nginxhello
  labels:
    app.kubernetes.io/name: nginxhello
    app.kubernetes.io/part-of: nginxhello
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: nginxhello
    app.kubernetes.io/part-of: nginxhello
