apiVersion: v1
kind: Service
metadata:
  name: numbers-api
  namespace: rng
  labels:
    app: numbers-api
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: numbers-api
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: numbers-api
  namespace: rng
  labels:
    account: numbers-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: numbers-api
  namespace: rng
  labels:
    app: numbers-api
    version: v1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: numbers-api
      version: v1
  template:
    metadata:
      labels:
        app: numbers-api
        version: v1
    spec:
      serviceAccountName: numbers-api
      containers:
      - image: sixeyed/numbers-api:psod-istio
        name: numbers-api
        resources:
          limits:
            cpu: 150m
            memory: 150Mi
        ports:
        - containerPort: 80
          name: http