apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-hpa
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-hpa
  template:
    metadata:
      labels:
        service: test-hpa
        app: test-hpa
    spec:
      containers:
      - image: nginx
        name: test-hpa
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 30m # make this pod consume a lot of CPU resource on node
            memory: 30Mi