apiVersion: cert-manager.io/v1alpha3
kind: Issuer
metadata:
  name: acme-letsencrypt-staging
  namespace: default
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Provide a valid email address
    email: you@your-hostname
    privateKeySecretRef:
      name: acme-letsencrypt-staging
    solvers:
    - http01:
        ingress:
          # Provide the class associated with your ingress controller (e.g. nginx)
          class: nginx
